"use client";

import { useEffect, useState } from "react";
import { CalendarPlus, Stethoscope } from "lucide-react";
import { apiClient, type FieldCampEntry } from "@/lib/api-client";
import type { Doctor, Product } from "@zivira/types";

function formatDate(iso?: string | null) {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso || null;
  return d.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

// Round 19 item 2 — Camp entry. Maps cleanly onto the admin's campEntry
// generic master: doctor/productsDisplayed reuse the existing
// /field/doctors and /field/products lookups (no new picker infra needed),
// and organizer is always the caller's own real name, forced server-side
// (never editable here) so one MR can never author an entry as someone
// else. campCode is auto-generated by the backend.
export function FieldCampEntryForm() {
  const [camps, setCamps] = useState<FieldCampEntry[]>([]);
  const [doctors, setDoctors] = useState<Doctor[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const [campName, setCampName] = useState("");
  const [campDate, setCampDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [hospital, setHospital] = useState("");
  const [doctor, setDoctor] = useState("");
  const [noOfPatients, setNoOfPatients] = useState("0");
  const [productsDisplayed, setProductsDisplayed] = useState("");
  const [remarks, setRemarks] = useState("");

  function load() {
    setLoading(true);
    setError("");
    Promise.all([apiClient.camps(), apiClient.doctors(), apiClient.products()])
      .then(([campsRes, doctorsRes, productsRes]) => {
        setCamps(campsRes.data);
        setDoctors(doctorsRes.data);
        setProducts(productsRes.data);
      })
      .catch((e) => setError(e instanceof Error ? e.message : "Unable to load camp data"))
      .finally(() => setLoading(false));
  }

  useEffect(() => { load(); }, []);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setError(""); setMessage("");
    if (!campName.trim()) { setError("Please enter a camp name."); return; }
    setSubmitting(true);
    try {
      await apiClient.submitCamp({
        campName: campName.trim(),
        campDate,
        hospital: hospital.trim(),
        doctor,
        noOfPatients: Number(noOfPatients) || 0,
        productsDisplayed,
        remarks: remarks.trim()
      });
      setMessage("Camp entry submitted.");
      setCampName(""); setHospital(""); setNoOfPatients("0"); setRemarks("");
      load();
    } catch (e2) {
      setError(e2 instanceof Error ? e2.message : "Unable to submit camp entry");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <>
      <section className="bg-white rounded-2xl p-4 border border-slate-200/90 shadow-card space-y-3.5">
        <div className="flex items-center justify-between pb-1 border-b border-slate-100">
          <span className="text-xs font-bold text-slate-900 flex items-center gap-1.5">
            <CalendarPlus size={15} className="text-emerald-700" /> New Camp Entry
          </span>
        </div>
        <form onSubmit={submit} className="space-y-3">
          <div className="space-y-1">
            <label className="text-[12px] font-bold text-slate-700">Camp Name</label>
            <input
              type="text" value={campName} onChange={(e) => setCampName(e.target.value)}
              className="w-full bg-white border border-slate-300 rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-800 shadow-2xs"
              placeholder="e.g. Diabetes Awareness Camp"
            />
          </div>
          <div className="grid grid-cols-2 gap-2.5">
            <div className="space-y-1">
              <label className="text-[12px] font-bold text-slate-700">Camp Date</label>
              <input type="date" value={campDate} onChange={(e) => setCampDate(e.target.value)} className="w-full bg-white border border-slate-300 rounded-xl px-3 py-2.5 text-xs font-semibold text-slate-800 shadow-2xs" />
            </div>
            <div className="space-y-1">
              <label className="text-[12px] font-bold text-slate-700">No. of Patients</label>
              <input type="number" min={0} value={noOfPatients} onChange={(e) => setNoOfPatients(e.target.value)} className="w-full bg-white border border-slate-300 rounded-xl px-3 py-2.5 text-xs font-semibold text-slate-800 shadow-2xs" />
            </div>
          </div>
          <div className="space-y-1">
            <label className="text-[12px] font-bold text-slate-700">Hospital</label>
            <input type="text" value={hospital} onChange={(e) => setHospital(e.target.value)} className="w-full bg-white border border-slate-300 rounded-xl px-3 py-2.5 text-xs font-semibold text-slate-800 shadow-2xs" placeholder="Hospital / venue name" />
          </div>
          <div className="space-y-1">
            <label className="text-[12px] font-bold text-slate-700">Doctor</label>
            <select value={doctor} onChange={(e) => setDoctor(e.target.value)} className="w-full bg-white border border-slate-300 rounded-xl px-3 py-2.5 text-xs font-semibold text-slate-800 shadow-2xs">
              <option value="">— Select doctor —</option>
              {doctors.map((d) => <option key={d.id} value={d.name}>{d.name}</option>)}
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[12px] font-bold text-slate-700">Product Displayed</label>
            <select value={productsDisplayed} onChange={(e) => setProductsDisplayed(e.target.value)} className="w-full bg-white border border-slate-300 rounded-xl px-3 py-2.5 text-xs font-semibold text-slate-800 shadow-2xs">
              <option value="">— Select product —</option>
              {products.map((p) => <option key={p.id} value={p.name}>{p.name}</option>)}
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[12px] font-bold text-slate-700">Remarks</label>
            <textarea value={remarks} onChange={(e) => setRemarks(e.target.value)} rows={2} className="w-full bg-white border border-slate-300 rounded-xl p-2.5 text-xs font-medium text-slate-700 shadow-2xs resize-none" />
          </div>
          {error && <p className="text-xs text-red-600 bg-red-50 p-2 rounded">{error}</p>}
          {message && <p className="text-xs text-emerald-700 bg-emerald-50 p-2 rounded">{message}</p>}
          <button type="submit" disabled={submitting} className="w-full py-3 text-sm font-black text-white bg-emerald-700 hover:bg-emerald-800 rounded-xl shadow-md disabled:opacity-60">
            {submitting ? "Submitting..." : "Submit Camp Entry"}
          </button>
        </form>
      </section>

      <section className="space-y-2.5">
        <h2 className="text-sm font-extrabold text-slate-900">Your Past Camps ({camps.length})</h2>
        {!loading && camps.length === 0 && <p className="text-sm text-slate-500 italic px-1">No camp entries submitted yet.</p>}
        {camps.map((c) => (
          <div key={c.id} className="bg-white rounded-2xl border border-slate-200/90 p-3.5 shadow-card space-y-1.5">
            <div className="flex items-start justify-between gap-2">
              <div className="flex items-center gap-2 min-w-0">
                <div className="w-8 h-8 rounded-lg bg-emerald-50 border border-emerald-200/70 flex items-center justify-center text-emerald-700 shrink-0"><Stethoscope size={14} /></div>
                <div className="min-w-0">
                  <h4 className="text-xs font-extrabold text-slate-900 truncate">{c.campName}</h4>
                  <p className="text-[10px] text-slate-500">{c.campCode} · {formatDate(c.campDate)}</p>
                </div>
              </div>
              <span className="shrink-0 text-[10px] font-bold text-slate-500">{c.noOfPatients ?? 0} patients</span>
            </div>
            {(c.hospital || c.doctor) && <p className="text-[11px] text-slate-600">{[c.hospital, c.doctor].filter(Boolean).join(" · ")}</p>}
          </div>
        ))}
      </section>
    </>
  );
}
